import { DietType, Language } from './types';

export const DIET_OPTIONS = [
  { value: DietType.NONE, label: 'No Restrictions' },
  { value: DietType.VEGAN, label: 'Vegan' },
  { value: DietType.VEGETARIAN, label: 'Vegetarian' },
  { value: DietType.KETO, label: 'Keto' },
  { value: DietType.GLUTEN_FREE, label: 'Gluten Free' },
  { value: DietType.PALEO, label: 'Paleo' },
];

export const DIET_LABELS: Record<Language, Record<string, string>> = {
  en: {
    [DietType.NONE]: 'No Restrictions',
    [DietType.VEGAN]: 'Vegan',
    [DietType.VEGETARIAN]: 'Vegetarian',
    [DietType.KETO]: 'Keto',
    [DietType.GLUTEN_FREE]: 'Gluten Free',
    [DietType.PALEO]: 'Paleo',
  },
  pt: {
    [DietType.NONE]: 'Sem Restrições',
    [DietType.VEGAN]: 'Vegano',
    [DietType.VEGETARIAN]: 'Vegetariano',
    [DietType.KETO]: 'Ceto',
    [DietType.GLUTEN_FREE]: 'Sem Glúten',
    [DietType.PALEO]: 'Paleo',
  }
};

export const MOCK_IMAGE_PLACEHOLDER = "https://picsum.photos/800/600";

export const TRANSLATIONS = {
  en: {
    navTitle: "CHEF GOURMET AI",
    poweredBy: "POWERED BY GEMINI",
    heroTitlePart1: "What's in your",
    heroTitlePart2: "kitchen",
    heroTitlePart3: "today?",
    heroSubtitle: "Upload a photo of your fridge or list your ingredients. Our AI Chef will curate a Michelin-star recipe just for you.",
    visualInspection: "1. Visual Inspection (Optional)",
    ingredientsNotes: "2. Ingredients & Notes",
    dietaryPreferences: "3. Dietary Preferences",
    askChef: "Ask the Chef",
    uploadPlaceholder: "Click to upload fridge photo or take a picture",
    uploadPlaceholderActive: "Click to change",
    ingredientsPlaceholder: "e.g., Chicken breast, lemon, thyme, garlic. I want something fast and zesty.",
    errorMissing: "Please provide ingredients or upload a photo.",
    thinking: "The Chef is thinking...",
    analyzing: "Analyzing ingredients and crafting your menu.",
    newOrder: "New Order",
    theMenu: "The Menu",
    cookingMode: "Cooking Mode",
    prep: "Prep",
    cook: "Cook",
    difficulty: "Difficulty",
    ingredients: "Ingredients",
    chefNotes: "Chef's Notes",
    summary: "Summary",
    summaryText: "This generated recipe is designed to be balanced and flavorful. Switch to Cooking Mode when you are ready to start preparing your meal.",
    startCooking: "Start Cooking",
    step: "Step",
    previous: "Previous",
    nextStep: "Next Step",
    bonAppetit: "Bon Appétit",
    nutritionTitle: "Nutritional Balance",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    langToggle: "PT-BR",
    myLovedOnes: "My Loved Ones",
    noFavorites: "No recipes saved yet. Start cooking to add some love!",
    viewRecipe: "Cook This",
    remove: "Remove",
    settings: "Settings",
    apiKeyLabel: "Gemini API Key",
    apiKeyPlaceholder: "Enter your Google Gemini API Key",
    save: "Save",
    apiKeyHelp: "Your key is stored locally in your browser and used only to communicate with Google."
  },
  pt: {
    navTitle: "CHEF GOURMET IA",
    poweredBy: "FEITO COM GEMINI",
    heroTitlePart1: "O que tem na sua",
    heroTitlePart2: "cozinha",
    heroTitlePart3: "hoje?",
    heroSubtitle: "Envie uma foto da sua geladeira ou liste seus ingredientes. Nosso Chef IA criará uma receita Michelin só para você.",
    visualInspection: "1. Inspeção Visual (Opcional)",
    ingredientsNotes: "2. Ingredientes e Notas",
    dietaryPreferences: "3. Preferências Alimentares",
    askChef: "Pedir ao Chef",
    uploadPlaceholder: "Clique para enviar foto da geladeira ou tirar uma foto",
    uploadPlaceholderActive: "Clique para alterar",
    ingredientsPlaceholder: "ex: Peito de frango, limão, tomilho, alho. Quero algo rápido e saboroso.",
    errorMissing: "Por favor, forneça ingredientes ou envie uma foto.",
    thinking: "O Chef está pensando...",
    analyzing: "Analisando ingredientes e criando seu menu.",
    newOrder: "Novo Pedido",
    theMenu: "O Menu",
    cookingMode: "Modo Cozinha",
    prep: "Preparo",
    cook: "Cozimento",
    difficulty: "Dificuldade",
    ingredients: "Ingredientes",
    chefNotes: "Notas do Chef",
    summary: "Resumo",
    summaryText: "Esta receita foi criada para ser equilibrada e saborosa. Mude para o Modo Cozinha quando estiver pronto para começar.",
    startCooking: "Começar a Cozinhar",
    step: "Passo",
    previous: "Anterior",
    nextStep: "Próximo Passo",
    bonAppetit: "Bom Apetite",
    nutritionTitle: "Balanço Nutricional",
    protein: "Proteína",
    carbs: "Carboidratos",
    fat: "Gordura",
    langToggle: "EN",
    myLovedOnes: "Meus Queridinhos",
    noFavorites: "Nenhuma receita salva. Comece a cozinhar para adicionar amor!",
    viewRecipe: "Cozinhar",
    remove: "Remover",
    settings: "Configurações",
    apiKeyLabel: "Chave API Gemini",
    apiKeyPlaceholder: "Insira sua chave da API Google Gemini",
    save: "Salvar",
    apiKeyHelp: "Sua chave é armazenada localmente no seu navegador e usada apenas para falar com o Google."
  }
};